package com.k3s.phoneserver

// This will be auto-generated by the Android build system
object BuildConfig {
    const val DEBUG = true
    const val APPLICATION_ID = "com.k3s.phoneserver"
    const val BUILD_TYPE = "debug"
    const val VERSION_CODE = 1
    const val VERSION_NAME = "1.0"
}
